#**Ejercicios de práctica NumPy y pandas**

**1. Importar la biblioteca**

Complete la importación con el alias convencional de la comunidad.

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


**2. Del listado al arreglo**

Convierta la lista de precios en un arreglo de NumPy

In [ ]:
precios = np.array([24000, 28000, 22000, 30000, 8000])
print(type(precios).__name__)
print(precios.dtype)


ndarray
int64


**3. Los tres atributos**

Averigüe la forma, el número de dimensiones y la cantidad de elementos.

In [ ]:
matriz = np.array([[2, 24000],
 [1, 28000],
 [3, 22000]])
print(matriz.shape) # forma
print(matriz.ndim) # dimensiones
print(matriz.size) # total de elementos

(3, 2)
2
6


**4. Secuencias automáticas**

Genere una secuencia con paso fijo, otra con extremos fijos y un arreglo de ceros

In [ ]:
secuencia = np.arange(0, 10, 2)
rango = np.linspace(0, 1, 5)
ceros = np.zeros(5)
print(secuencia)
print(rango)
print(ceros.dtype)

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
float64


**5. Corrección: falta algo**

Este bloque lanza TypeError: array() takes from 1 to 2 positional arguments but 3 were given.

In [ ]:
precios = np.array([24000, 28000, 22000])
print(precios)

[24000 28000 22000]


**6. Multiplicar dos arreglos**

Calcule el ingreso de cada transacción multiplicando elemento por elemento.

In [ ]:
cantidades = np.array([2, 1, 3, 2, 1])
precios = np.array([24000, 28000, 22000, 30000, 8000])
ingresos = cantidades*precios
print(ingresos)

[48000 28000 66000 60000  8000]


**7. El escalar se estira**

Aplique un descuento del diez por ciento a todos los precios.

In [ ]:
con_descuento = precios* 0.9
print(con_descuento)
print(con_descuento.dtype)

[21600. 25200. 19800. 27000.  7200.]
float64


**8. El mismo cálculo, dos formas**

Escriba con NumPy lo que el ciclo hace con listas.


In [ ]:
# con listas de Python
lista = [24000, 28000, 22000, 30000, 8000]
resultado = []
for p in lista:
 resultado.append(p * 1.19)

# con NumPy, en una sola línea
resultado_np =np.array(lista)* 1.19
print(resultado_np)


[28560. 33320. 26180. 35700.  9520.]


**9. Predicción: lista o arreglo**

El mismo operador sobre dos estructuras distintas.

In [ ]:
lista = [1, 2, 3]
arreglo = np.array([1, 2, 3])
print(lista * 2)
print(arreglo * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


**10. Predicción: formas distintas**

Un arreglo de cinco elementos multiplicado por uno de cuatro.

*5 elementos × 4 elementos → no son compatibles, por lo que a * b genera ValueError*

In [ ]:
a = np.array([2, 1, 3, 2, 1])
b = np.array([10, 20, 30, 40, 50])
print(a * b)

[20 20 90 80 50]


**11. Corrección: el ciclo sobra**

El bloque funciona, pero desaprovecha NumPy por completo.

*Respuesta: ingresos = cantidades * precios y la ventaja principal es la vectorización, que suele ser más eficiente y hace el código más limpio.*

In [ ]:
ingresos = np.zeros(5)

ingresos = cantidades*precios

print(ingresos)

[48000 28000 66000 60000  8000]


**12. Primero, último y una porción**

Obtenga elementos por posición sin contar cuántos hay.

In [ ]:
print(precios[0]) # el primero
print(precios[-1]) # el último
print(precios[0:3]) # las posiciones 1, 2 y 3

24000
8000
[24000 28000 22000]


**13. La máscara booleana**

Construya la condición y úsela para filtrar.

In [ ]:
mascara = precios > 20000
print(mascara)
print(precios[mascara])
print(precios[mascara].sum())

[ True  True  True  True False]
[24000 28000 22000 30000]
104000


**14. Dos condiciones a la vez**

Precios mayores a 10.000 y menores a 29.000. Recuerde el operador correcto

In [ ]:
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)


[24000 28000 22000]


**15. Etiquetar según una condición**

Clasifique cada precio sin escribir un ciclo ni un if.

In [ ]:
etiquetas = np.where(precios > 25000, "alto", "normal")
print(etiquetas)

['normal' 'alto' 'normal' 'alto' 'normal']


**16. Contar y sumar lo filtrado**

Cuántos elementos cumplen la condición y cuánto suman.

In [ ]:
caros = precios[precios > 20000]
print(caros.size) # cuántos son
print(caros.sum()) # cuánto suman


4
104000


**17. Corrección: el operador equivocado**

Este bloque lanza ValueError: The truth value of an array with more than one element is
ambiguous.


In [ ]:
seleccion = precios[(precios > 10000) & (precios < 29000)]
print(seleccion)

[24000 28000 22000]


**18. Las funciones de resumen**

Complete cada línea con el método que corresponde

In [ ]:
ingresos = np.array([48000, 28000, 66000, 60000, 8000])
print(ingresos.sum()) # 210000
print(ingresos.mean()) # 42000.0
print(ingresos.max()) # 66000
print(round(ingresos.std(), 2))


210000
42000.0
66000
21391.59


**19. Sumar por columna**

Cada fila es un producto y cada columna una sede. Obtenga el total de cada sede.

In [ ]:
matriz = np.array([[48000, 28000],
 [66000, 60000],
 [ 8000, 12000]])
print(matriz.sum(axis=0))

[122000 100000]


**20. Sumar por fila y en total**

Ahora el total de cada producto y el total general.

In [ ]:
print(matriz.sum(axis=1))
print(matriz.sum())


[ 76000 126000  20000]
222000


**21. Predicción: el eje que confunde**

Sin ejecutar nada todavía, escriba su predicción y después compruébela.

In [ ]:
print(matriz.mean(axis=0))

[40666.66666667 33333.33333333]


**22. Crear e inspeccionar el DataFrame**

Convierta la lista de diccionarios del caso en una tabla y revise su estructura

**Cargar datos en CSV**

In [ ]:
import pandas as pd
df_ventas=pd.read_csv("datos_ventas.csv",sep=";") #encoding="latin1"
df_ventas.head()


,fecha,cliente,producto,categoria,cantidad,precio_unitario,costo_unitario,sede
0,3/08/2026,101,Bowl Andino,Almuerzo,2,"24.000,00","14.000,00",centro
1,3/08/2026,102,Pasta Urbana,Almuerzo,1,"28.000,00","17.000,00",NORTE
2,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
3,4/08/2026,103,Bowl Andino,Almuerzo,1,"24.000,00","14.000,00",Centro
4,4/08/2026,104,Hamburguesa Central,Cena,2,"30.000,00","19.000,00",Norte


In [ ]:
#conversion de formato de fechadf_ventas = pd.DataFrame(datos_ventas)
df_ventas["fecha"] = pd.to_datetime(df_ventas["fecha"], dayfirst=True)

print(df_ventas.shape)
print(df_ventas.head(3))

(19, 8)
       fecha  cliente      producto categoria  cantidad precio_unitario  \
0 2026-08-03      101   Bowl Andino  Almuerzo         2       24.000,00   
1 2026-08-03      102  Pasta Urbana  Almuerzo         1       28.000,00   
2 2026-08-04      103   Bowl Andino  Almuerzo         1       24.000,00   

  costo_unitario     sede  
0      14.000,00   centro  
1      17.000,00    NORTE  
2      14.000,00  Centro   


**23. Una columna o varias**

Complete los corchetes para obtener primero una Series y después un DataFrame.


In [ ]:
una = df_ventas["producto"]
varias = df_ventas[["producto", "cantidad"]]

print(type(una).__name__, type(varias).__name__)

Series DataFrame


**24. Predicción: qué hay debajo de una columna**

pandas está construido sobre NumPy. Compruébelo.

*relación: pandas → Series → NumPy ndarray.*

In [ ]:
arreglo = df_ventas["cantidad"].to_numpy()
print(type(arreglo).__name__)
print(arreglo.sum())


ndarray
32


In [ ]:
print(df_ventas.loc[0:2].shape[0])
print(df_ventas.loc[0:2].shape[1])

print(df_ventas.iloc[0:2].shape[0])
print(df_ventas.iloc[0:2].shape[1])


3
8
2
8


In [ ]:
mascara = (
    (df_ventas["sede"] == "Centro")
    & (df_ventas["categoria"] == "Almuerzo")
)

seleccion = df_ventas.loc[mascara].copy()

print(seleccion.shape[0], seleccion["cantidad"].sum())


3 7


In [ ]:
from google.colab import drive
drive.mount('/content/drive')